baseURL = "https://example.com/"
languageCode = "en"

title = "Example Site"
theme = "antora-default-ui-hugo-theme"

copyright = "Acme Corp. All rights reserved."
paginate = 3

[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  keywords = ["foo", "bar"]
  editThisPage = "https://github.com/basil/antora-default-ui-hugo-theme/edit/master/exampleSite/content/"
  since = 2020

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false
